# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_job"
  build_job:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Making the executable to run
        run: |
          pwd
          ls
          whoami
          cd src
          make
          ls

      - name: Uploading the executable for later...
        uses: actions/upload-artifact@v3
        with:
          name: mainExecutable
          path: src/helloWorld.exe
          retention-days: 1

  test_job:
    runs-on: self-hosted

    needs: build_job

    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts from build stage...

        # putting "uses" clause in a step means we cannot have our
        # own bash script here!
        uses: actions/download-artifact@v3

        # comment out the next two lines to just download
        # all artifacts
        with:
          name: mainExecutable


      - name: Run the executable from before
        run: |
          whoami
          pwd
          echo "helloWorld.exe should already be present..."
          ls
          echo "move the executable from top-level down to src"
          mv helloWorld.exe src
          cd src
          echo "making it executable..."
          chmod +x helloWorld.exe
          ls
          ./helloWorld.exe
